---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Super-Linter
      uses: super-linter/super-linter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHON_PYLINT_CONFIG_FILE: .python-lint
        VALIDATE_PYTHON_PYLINT: true
        VALIDATE_GITLEAKS: true
        LINTER_RULES_PATH: /
